### ISSUE TITLE
How do I connect anna-rs in the Rust program without WasmEdge?

### ISSUE THREAD

**Issue by JasonLou99** [essa-project/anna-rs#3]

**Comment by JasonLou99** [comment]
I have learned that anna-rs can be connected through wasmedge-anna-client, but is there any way to directly use RUST to connect?

**Comment by stdrc** [comment]
> I have learned that anna-rs can be connected through wasmedge-anna-client, but is there any way to directly use RUST to connect?

You can checkout the code in https://github.com/essa-project/anna-rs/blob/main/src/nodes/client/interactive.rs to see how to use `ClientNode`. This is the original client of anna-rs, which can run on Linux or other operating systems instead of WamsEdge.
